
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s [%(levelname)s] [%(module)s.%(funcName)s] %(message)s"
  detailed_threads:
    format: "%(asctime)s [%(levelname)-5s] (%(threadName)-12s) [%(funcName)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  proxy_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: proxy.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  network_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed_threads
    filename: network.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  # error_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: ERROR
  #   formatter: detailed
  #   filename: errors.log
  #   backupCount: 20
  #   encoding: utf8

loggers:
  proxy:
    level: INFO
    handlers: [console, proxy_file_handler]
    propagate: no

  network:
    level: INFO
    handlers: [console, network_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler]
